# Generated by Django 5.0.3 on 2024-03-08 22:44

import django.utils.timezone
import helpers.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publication_date', models.DateTimeField()),
                ('isbn', models.CharField(max_length=20, validators=[helpers.utils.validate_isbn])),
                ('genre', models.CharField(choices=[('FIC', 'Fiction'), ('NF', 'Non-Fiction'), ('SCI', 'Science'), ('HIS', 'History'), ('FAN', 'Fantasy'), ('BIO', 'Biography'), ('THR', 'Thriller'), ('ROM', 'Romance'), ('OTHERS', 'Others')], max_length=12)),
                ('price', models.FloatField(default=0.0)),
                ('stock', models.IntegerField(default=0)),
                ('qty_sold', models.IntegerField(default=0)),
                ('qty_left', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
