# Generated by Django 5.0.3 on 2024-03-08 23:00

import helpers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default=helpers.models.generate_id, editable=False, max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='qty_left',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
