# Generated by Django 5.0.3 on 2024-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CANCELED', 'CANCELED'), ('DELIVERED', 'DELIVERED')], default='OPEN', max_length=9, verbose_name='Order state'),
        ),
    ]
